TIME_SLOTS = ["morning", "afternoon", "evening"]
ACTIVITY_CATEGORIES = {"activity", "theme_park", "local_experience"}
ARRIVAL_DAY_CATEGORIES = {"food", "shopping", "relax", "culture", "photo", "cafe"}
MIDDLE_DAY_CATEGORIES = {"activity", "theme_park", "local_experience", "nature", "sightseeing"}
DEPARTURE_DAY_CATEGORIES = {"food", "shopping", "relax", "culture", "photo", "sightseeing"}
DEFAULT_CONCEPTS = ["sightseeing"]
DEFAULT_STYLE = "easy"
DEFAULT_COMPANION = "friend"
DEFAULT_CITY_BY_COUNTRY = {
    "korea": "seoul",
    "south korea": "seoul",
}
SLOT_CATEGORY_PREFERENCE = {
    "morning": {"relax", "nature", "cafe", "sightseeing", "culture", "activity", "local_experience"},
    "afternoon": {"sightseeing", "shopping", "culture", "activity", "nature", "theme_park", "local_experience"},
    "evening": {"food", "shopping", "relax", "photo", "nightlife", "activity", "theme_park", "local_experience"},
}
SEOUL_AREA_ROUTE_ORDER = [
    "jongno",
    "euljiro",
    "myeongdong",
    "dongdaemun",
    "seongsu",
    "hongdae",
    "yeouido",
    "gangnam",
    "jamsil",
    "itaewon",
]
SEOUL_AREA_NEIGHBORS = {
    "jongno": {"euljiro", "myeongdong", "dongdaemun"},
    "euljiro": {"jongno", "myeongdong", "dongdaemun"},
    "myeongdong": {"jongno", "euljiro", "namsan", "dongdaemun"},
    "dongdaemun": {"jongno", "euljiro", "myeongdong"},
    "seongsu": {"gangnam", "jamsil"},
    "hongdae": {"yeouido"},
    "yeouido": {"hongdae"},
    "gangnam": {"seongsu", "jamsil", "itaewon"},
    "jamsil": {"gangnam", "seongsu"},
    "itaewon": {"gangnam", "namsan"},
    "namsan": {"myeongdong", "itaewon"},
}
BUSAN_AREA_ROUTE_ORDER = [
    "nampo",
    "songdo",
    "gwangalli",
    "haeundae",
]
BUSAN_AREA_NEIGHBORS = {
    "nampo": {"songdo"},
    "songdo": {"nampo"},
    "gwangalli": {"haeundae"},
    "haeundae": {"gwangalli"},
}
JEJU_AREA_ROUTE_ORDER = [
    "east-jeju",
    "seongsan",
    "seogwipo-west",
    "west-jeju",
]
JEJU_AREA_NEIGHBORS = {
    "east-jeju": {"seongsan"},
    "seongsan": {"east-jeju"},
    "seogwipo-west": {"west-jeju"},
    "west-jeju": {"seogwipo-west"},
}
PLACE_NAME_KO = {
    "gyeongbokgung": "경복궁",
    "bukchon": "북촌한옥마을",
    "insadong": "인사동 거리",
    "myeongdong": "명동",
    "namsan-tower": "N서울타워",
    "hongdae": "홍대",
    "yeouido-hangang": "여의도 한강공원",
    "gangnam": "강남역 일대",
    "coex": "코엑스몰과 별마당도서관",
    "asakusa-sensoji": "센소지와 나카미세 거리",
    "ueno-park": "우에노 공원",
    "ameyoko": "아메요코 시장거리",
    "shibuya": "시부야 스크램블 교차로와 센터가이",
    "meiji-jingu": "메이지 신궁",
    "harajuku": "다케시타 거리와 하라주쿠",
    "tsukiji": "츠키지 장외시장",
    "ginza": "긴자",
    "odaiba": "오다이바 해변 지구",
    "dotonbori": "도톤보리",
    "kuromon-market": "구로몬 시장",
    "osaka-castle": "오사카성",
    "shinsaibashi": "신사이바시 쇼핑 아케이드",
    "tsutenkaku": "쓰텐카쿠와 신세카이",
    "umeda-sky": "우메다 스카이 빌딩",
    "nakazakicho": "나카자키초 카페 거리",
    "tennoji-park": "덴노지 공원",
    "sumiyoshi-taisha": "스미요시 타이샤",
    "grand-palace": "방콕 왕궁",
    "wat-pho": "왓 포",
    "wat-arun": "왓 아룬",
    "yaowarat": "야오와랏 로드",
    "chatuchak": "짜뚜짝 시장",
    "iconsiam": "아이콘시암",
    "lumpini": "룸피니 공원",
    "siam": "시암 스퀘어",
    "asiatique": "아시아티크 리버프론트",
    "arbat-street": "아르바트 거리",
    "sportivnaya-embankment": "스포르티브나야 해안 산책로",
    "tokarevsky-lighthouse": "토카레브스키 등대",
    "revolution-square": "혁명광장",
    "railway-station": "블라디보스토크 기차역",
    "svetlanskaya-street": "스베틀란스카야 거리",
    "eagle-nest": "이글스 네스트 전망대",
    "millionka": "밀리온카 지구",
    "cafe-tour-center": "도심 카페 코스",
    "eiffel-tower": "에펠탑",
    "louvre": "루브르 박물관",
    "montmartre": "몽마르트르",
    "seine-river": "센강 산책로",
    "le-marais": "르 마레",
    "orsay": "오르세 미술관",
    "luxembourg": "뤽상부르 공원",
    "saint-germain": "생제르맹",
    "lotte-world-adventure": "롯데월드 어드벤처",
    "e-land-hangang-cruise": "이랜드 한강 크루즈",
    "aqua-planet-jeju": "아쿠아플라넷 제주",
    "jeju-rail-bike": "제주레일바이크",
    "jeonju-hanok-hanbok-experience": "전주한옥마을 한복 체험",
    "hanbyeok-traditional-play": "한벽문화관 전통놀이 체험",
    "toei-kyoto-studio-park": "도에이 교토 스튜디오 파크",
    "sagano-romantic-train": "사가노 로맨틱 트레인",
    "disneyland-paris": "디즈니랜드 파리",
    "vedettes-du-pont-neuf-cruise": "베데트 뒤 퐁네프 센강 크루즈",
    "bioparco-di-roma": "비오파르코 디 로마",
    "cinecitta-world": "치네치타 월드",
    "tibidabo-amusement-park": "티비다보 놀이공원",
    "montjuic-cable-car": "몬주익 케이블카",
    "tokyo-disneysea": "도쿄 디즈니씨",
    "universal-studios-japan": "유니버설 스튜디오 재팬",
    "universal-studios-singapore": "유니버설 스튜디오 싱가포르",
    "maokong-gondola": "마오콩 곤돌라",
    "taipei-childrens-amusement-park": "타이베이 어린이 놀이공원",
    "marine-world-uminonakamichi": "마린월드 우미노나카미치",
    "fukuoka-open-top-bus": "후쿠오카 오픈톱버스",
    "chiang-mai-night-safari": "치앙마이 나이트 사파리",
    "chiang-mai-celadon-workshop": "치앙마이 셀라돈 워크숍",
    "skyline-luge-busan": "스카이라인 루지 부산",
    "haslla-art-world": "하슬라아트월드",
    "gyeongju-expo-grand-park": "경주엑스포대공원",
    "mahanakhon-skywalk": "마하나콘 스카이워크",
    "night-safari-singapore": "싱가포르 나이트 사파리",
}
AREA_LABEL_KO = {
    "jongno": "종로",
    "myeongdong": "명동",
    "namsan": "남산",
    "hongdae": "홍대",
    "yeouido": "여의도",
    "gangnam": "강남",
    "seongsu": "성수",
    "itaewon": "이태원",
    "jamsil": "잠실",
    "dongdaemun": "동대문",
    "euljiro": "을지로",
    "haeundae": "해운대",
    "gwangalli": "광안리",
    "nampo": "남포",
    "dongnae": "동래",
    "centum": "센텀시티",
    "gwangjin": "광진",
    "gwanak": "관악",
    "songdo": "송도",
    "east-jeju": "제주 동부",
    "west-jeju": "제주 서부",
    "seogwipo-west": "서귀포 서부",
    "asakusa": "아사쿠사",
    "ueno": "우에노",
    "yanaka": "야나카",
    "shibuya": "시부야",
    "harajuku": "하라주쿠",
    "ginza": "긴자",
    "odaiba": "오다이바",
    "roppongi": "롯폰기",
    "akihabara": "아키하바라",
    "kiyosumi": "기요스미",
    "kichijoji": "기치조지",
    "ebisu": "에비스",
    "namba": "난바",
    "castle-area": "오사카성 일대",
    "shinsekai": "신세카이",
    "umeda": "우메다",
    "tennoji": "덴노지",
    "sumiyoshi": "스미요시",
    "bay-area": "베이 에어리어",
    "nakanoshima": "나카노시마",
    "fukushima": "후쿠시마",
    "old-city": "올드타운",
    "riverside": "리버사이드",
    "chinatown": "차이나타운",
    "chatuchak": "짜뚜짝",
    "silom": "실롬",
    "siam": "시암",
    "green-zone": "그린존",
    "ari": "아리",
    "asok": "아속",
    "city-center": "도심",
    "sentosa": "센토사",
    "seaside": "해안가",
    "tokarevsky": "토카레브스키",
    "russky-island": "루스키섬",
    "viewpoint": "전망대 일대",
    "suburb": "외곽",
    "canal": "운하 주변",
    "bercy": "베르시",
    "seongsan": "성산",
    "gujwa": "구좌",
    "hanok-village": "전주한옥마을",
    "jeonjucheon": "전주천",
    "uzumasa": "우즈마사",
    "arashiyama": "아라시야마",
    "marne-la-vallee": "마른라발레",
    "ile-de-la-cite": "시테섬",
    "villa-borghese": "빌라 보르게세",
    "castel-romano": "카스텔 로마노",
    "tibidabo": "티비다보",
    "montjuic": "몬주익",
    "wenshan": "원산",
    "shilin": "스린",
    "osiria": "오시리아",
    "gangdong": "강동",
    "bomun": "보문",
    "mandai": "만다이",
}
CONCEPT_LABEL_KO = {
    "food": "식사",
    "shopping": "쇼핑",
    "relax": "휴양",
    "sightseeing": "관광",
    "culture": "문화",
    "nature": "자연",
    "activity": "액티비티",
    "nightlife": "나이트라이프",
    "onsen": "온천",
}
COMPANION_REASON_KO = {
    "solo": "혼자서도 부담 없이 움직이기 좋습니다.",
    "couple": "둘이서 분위기 있게 시간을 보내기 좋습니다.",
    "friend": "친구와 함께 즐기기 좋은 활기 있는 동선입니다.",
    "family": "가족과 함께 무리 없이 둘러보기 좋습니다.",
}
TIME_SLOT_REASON_KO = {
    "morning": "오전에 가볍게 시작하기 좋고",
    "afternoon": "하루의 핵심 일정으로 넣기 좋고",
    "evening": "저녁 시간에 여유롭게 마무리하기 좋고",
}
BUDGET_REASON_KO = {
    "low": "가성비를 살리기 좋으며",
    "medium": "비용과 만족도의 균형이 잘 맞고",
    "high": "조금 더 편안하고 완성도 있는 여행 예산과 잘 맞으며",
}
